### PR TITLE
fix detached option

### PR DESCRIPTION
**Pull request by hashfriend**
Small typo in the [`detached` arg](https://nodejs.org/api/child_process.html#child_processforkmodulepath-args-options).

### CODE REVIEW

**Comment by Alex0779** [comment]
Hello .. is the Alchemy still valid and good to use?? if no please indicate so i can change the API 
thank you

**Comment by boyella143** [comment]
yeah i am unable to see balances weather they are 0 or not? is alchemy working?

**Comment by Ak535Ak** [comment]
I am sorry for my ignorance, i didnt found issues tab. But should i run check-balances.js separatly for balance checking or when i hit index.js it does in automatic way ? thx in advance.

**Comment by YashvirGaming** [comment]
### **how about it captures Balance + the 12 Seed phrases also**

**Comment by Helloworldyoufuckingsuck** [comment]
How To fix network error when i try to check balances

**Pull request closed without merging**
